name: "CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "master"

jobs:
  test:
    runs-on: "ubuntu-22.04"

    steps:
      - uses: "actions/checkout@v2"

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - name: "Install CI dependencies"
        run: |
          ./run ci:install-deps

      - name: "Test"
        run: |
          # Remove volumes in CI to avoid permission errors due to UID / GID.
          sed -i "s|.:/app|/tmp:/tmp|g" .env*
          sed -i "s|.:/app|/tmp:/tmp|g" docker-compose.yml

          # Django requires static files to be collected in order to run its
          # test suite. That means we need to generate production assets from
          # esbuild. This line ensures NODE_ENV is set to production.
          sed -i "s|export NODE_ENV|#export NODE_ENV|g" .env*
          
          docker-compose --help
          
          DEBUG=false NODE_ENV=production ./run ci:test
          
          git diff --exit-code -- src/ || (echo "Code is not formatted properly. Run ./run quality" && exit 1)
